// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJYE8RMG8ljdN6ej7463TdaVg5K2sw27E',
    appId: '1:599224735397:android:4b186da636ff9e2c0c9f4c',
    messagingSenderId: '599224735397',
    projectId: 'pothole-detection-1fe25',
    storageBucket: 'pothole-detection-1fe25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl9pqG8X0hUOkiDUFs2rcc2ECt1NNmP5E',
    appId: '1:599224735397:ios:f5b837e24a1a4a9e0c9f4c',
    messagingSenderId: '599224735397',
    projectId: 'pothole-detection-1fe25',
    storageBucket: 'pothole-detection-1fe25.appspot.com',
    androidClientId: '599224735397-6ss6ajlcabjamc8ikua6c9dp9a09pqk1.apps.googleusercontent.com',
    iosClientId: '599224735397-dams2kjr1hcr50vc28p0fp5mgdoimtsv.apps.googleusercontent.com',
    iosBundleId: 'com.example.mvpworking',
  );
}
